homepage/urls.py
from django.urls import path
from .views import homepage

urlpatterns = [
    path('', homepage, name='homepage')

jurassic/urls.py
from django.contrib import admin
from django.urls import path, include
from homepage.views import homepage
urlpatterns = [
       path('admin/', admin.site.urls),
       path('', homepage, name="homepage"),
       path('parent/', include('lowestParent.urls', namespace='parent')),
       path('siblings/', include('siblings.urls', namespace='siblings')),
       path('form/', include('smartInput.urls', namespace='smart_form'))
]

lowestParent/urls.py
from django.urls import path
from .views import lowestParent, lowestParent_post
app_name = "parent"

urlpatterns = [
    path('', lowestParent, name='lowest-parent'),
    path('get', lowestParent_post, name='lowest-parent-post')
]

siblings/urls.py
from django.urls import path
from .views import siblings, siblings_post
app_name = "siblings"

urlpatterns = [
    path('', siblings, name='siblings'),
    path('send', siblings_post, name='sibling-post')
]

smartInput/urls.py
from django.urls import path
from .views import smart_form, get_animal_name, get_animal_info
app_name = "smart_form"

urlpatterns = [
    path('', smart_form, name='smart_form'),
    path('get-animal-name/', get_animal_name, name='get_animal_name'),
    path('get-animal-info/<str:name>/', get_animal_info, name='get_animal_info')
]

templates/partials/footer.html
{% load static %}
<footer id="gtco-footer" role="contentinfo" style="height: 5%;">
	<div class="row copyright">
		<div class="col-md-12">
			<p class="pull-left" style="margin-left: 2%;">
				<small class="block">&copy; Big Brothers. All Rights Reserved.</small> 
				<small class="block">Designed by Big Brothers</small>
			</p>
			<p class="pull-right" style="margin-right: 2%;">
				<ul class="gtco-social-icons pull-right">
					<li><a href="https://gitlab.com/michael09/big-brothers"><i class="icon-github"></i></a> </li>
					<li><a href="https://drive.google.com/open?id=1ituctfaxYU-PJvlBwr3hR-tjATGPjBZU"><i class="icon-google"></i></a></li>
				</ul>
			</p>
		</div>
	</div>
</footer>

templates/partials/navbar.html
{% load static %}
<header>
    <nav class="gtco-nav" role="navigation">
		<div class="gtco-container">
			<div class="row">
				<div class="col-xs-2">
					<div id="gtco-logo" style="font-size: 14px;"><a href="{% url 'homepage' %}"><img src="{% static 'images/diplodocus.png' %}" style="width: 28px;"> Jurassic Tree</a></div>
				</div>
				<div class="col-xs-10 text-right menu-1">
					<ul>
						{% if "parent" in request.path %}
						<li><a href="{% url 'homepage' %}">Home</a></li>
						<li class="active"><a href="{% url 'parent:lowest-parent' %}">Find Parent</a></li>
						<li><a href="{% url 'siblings:siblings' %}">Find Siblings</a></li>
						<li><a href="{% url 'smart_form:smart_form' %}">Find Info</a></li>
						{% elif "siblings" in request.path %}
						<li><a href="{% url 'homepage' %}">Home</a></li>
						<li><a href="{% url 'parent:lowest-parent' %}">Find Parent</a></li>
						<li class="active"><a href="{% url 'siblings:siblings' %}">Find Siblings</a></li>
						<li><a href="{% url 'smart_form:smart_form' %}">Find Info</a></li>
						{% elif "form" in request.path %}
						<li><a href="{% url 'homepage' %}">Home</a></li>
						<li><a href="{% url 'parent:lowest-parent' %}">Find Parent</a></li>
						<li><a href="{% url 'siblings:siblings' %}">Find Siblings</a></li>
						<li class="active"><a href="{% url 'smart_form:smart_form' %}">Find Info</a></li>
						{% else %}
						<li class="active"><a href="{% url 'homepage' %}">Home</a></li>
						<li><a href="{% url 'parent:lowest-parent' %}">Find Parent</a></li>
						<li><a href="{% url 'siblings:siblings' %}">Find Siblings</a></li>
						<li><a href="{% url 'smart_form:smart_form' %}">Find Info</a></li>
						{% endif %}
					</ul>
				</div>
			</div>
			
		</div>
	</nav>
</header>