homepage/urls.py
from django.urls import path
from .views import homepage

urlpatterns = [
    path('', homepage, name='homepage')

jurassic/urls.py
from django.contrib import admin
from django.urls import path, include
from homepage.views import homepage
urlpatterns = [
       path('admin/', admin.site.urls),
       path('', homepage, name="homepage"),
       path('parent/', include('lowestParent.urls', namespace='parent')),
       path('siblings/', include('siblings.urls', namespace='siblings')),
       path('form/', include('smartInput.urls', namespace='smart_form'))
]

siblings/urls.py
from django.urls import path
from .views import siblings, siblings_post
app_name = "siblings"

urlpatterns = [
    path('', siblings, name='siblings'),
    path('send', siblings_post, name='sibling-post')
]

siblings/models.py
from django.db import models

# Create your models here.

siblings/views.py
from django.shortcuts import render
from homepage.models import TaxonomicUnits
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.http import HttpResponseBadRequest


# Create your views here.


def siblings(request):
    return render(request, 'siblings/siblings.html')


@require_POST
def siblings_post(request):
    animal_string = request.POST.get('animal')
    animal = None
    try:
        animal = TaxonomicUnits.objects.filter(complete_name__iexact=animal_string)[0]
        if animal.rank_id.rank_name.strip() != "Species" or animal.parent_tsn.rank_id == 0:
            raise Exception
    except Exception:
        return HttpResponseBadRequest()
    hierarchy = animal.hierarchy.hierarchy_string.strip().split("-")
    popLastElementsAndReverse(hierarchy)
    lst_sibling = TaxonomicUnits.objects.filter(parent_tsn=animal.parent_tsn).values_list("complete_name", 'tsn')[:10]
    res = makeTree(hierarchy, lst_sibling)
    result = {
        'nodeStructure': res[0]
    }
    return JsonResponse({'result': result})


def makeTree(hierarchy, lst_sibling):
    res = [{
        'text':
            {'name': name[0]},
        'HTMLclass': 'the-parent',
        'stackChildren': True
        ,
        'children': [{'text': {'name': name_child}} for name_child in TaxonomicUnits.objects
            .filter(parent_tsn=name[1]).values_list("complete_name", flat=True)]
    } for name in lst_sibling]

    for i in hierarchy:
        taxon = TaxonomicUnits.objects.get(tsn=i)
        tmp = [{
            'text': {'name': taxon.complete_name, 'desc': taxon.rank_id.rank_name},
            'HTMLclass': 'the-parent',
            'children': res
        }]
        res = tmp
    return res


def popLastElementsAndReverse(hierarchy):
    length = len(hierarchy)
    hierarchy.pop(length - 1)
    hierarchy.reverse()

siblings/templates/siblings/siblings.html
{% extends 'base.html' %}
{% load static %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'css/Treant/Treant.css' %}">
    <link rel="stylesheet" href="{% static 'siblings/css/example6.css' %}">
    <link rel="stylesheet" href="{% static 'js/vendor/perfect-scrollbar/perfect-scrollbar.css' %}">
    <link rel="stylesheet" href="{% static 'siblings/css/error.css' %}">
{% endblock %}

{% block content %}
    <div id="page">
        <header id="gtco-header" class="gtco-cover" role="banner" style="background-image: url('{% static 'siblings/images/forest.jpg' %}')">
            <div class="overlay"></div>
            <div class="gtco-container">
                <div class="row">

                    <div class="col-md-12 col-md-offset-0 text-center">

                        <div class="display-t">
                            <div class="display-tc" data-animate-effect="fadeIn" style="vertical-align: top;">
                                <h1 style="margin-top: 120px">FIND SIBLINGS</h1>
                                <br>
                                <div>
                                    <form class="form-inline" id="sibling" action="{% url 'siblings:sibling-post' %}">
                                        {% csrf_token %}
                                        <input id="animal" style="color: white; border-color: white; width: 40%" class="form-control bg-info" name="animal" type="search" placeholder="What animal's siblings are you searching for?" aria-label="Search" required>
                                        <button class="btn btn-outline-success" type="submit" style="font-size: 20px; color: white; background-color: #F75B17" onclick="window.location.href='#OrganiseChart6'">Search</button>
                                    </form>
                                </div>
                                <div>
                                    <br>
                                    <p style="color: white;">Find Sibling feature searches for the nearest sibling of an animal species. This feature will use forward chaining to find the sibling of an animal species. Apart from showing it's sibling, it will also show the tree that links between the two siblings to the same parent.</p>
                                </div>
                            </div>
                        </div>
                        <div id="error"></div>
                    </div>
                </div>
            </div>
        </header>
        <div id="gtco-features">
            <div class="gtco-container">
                <div class="chart" id="OrganiseChart6"></div>
            </div>
        </div>

        <div class="gototop js-top">
            <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
        </div>
    </div>
    
{% endblock %}

{% block extrascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.devbridge-autocomplete/1.2.27/jquery.autocomplete.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- jQuery Easing -->
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <!-- Waypoints -->
    <script src="{% static 'js/jquery.waypoints.min.js'%}"></script>
    <!-- Carousel -->
    <script src="{% static 'js/owl.carousel.min.js'%}"></script>
    <!-- countTo -->
    <script src="{% static 'js/jquery.countTo.js'%}"></script>
    <!-- Magnific Popup -->
    <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
    <script src="{% static 'js/magnific-popup-options.js'%}"></script>
    <!-- Main -->


    <script src="{% static 'js/vendor/raphael.js' %}"></script>
    <script src="{% static 'js/treant/Treant.js' %}"></script>
    <script src="{% static 'js/main.js'%}"></script>

    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/vendor/jquery.mousewheel.js' %}"></script>
    <script src="{% static 'js/vendor/perfect-scrollbar/perfect-scrollbar.js' %}"></script>

    <script src="{% static 'siblings/js/ajax.js' %}"></script>
{% endblock %}