homepage/urls.py
from django.urls import path
from .views import homepage

urlpatterns = [
    path('', homepage, name='homepage')

jurassic/urls.py
from django.contrib import admin
from django.urls import path, include
from homepage.views import homepage
urlpatterns = [
       path('admin/', admin.site.urls),
       path('', homepage, name="homepage"),
       path('parent/', include('lowestParent.urls', namespace='parent')),
       path('siblings/', include('siblings.urls', namespace='siblings')),
       path('form/', include('smartInput.urls', namespace='smart_form'))
]

lowestParent/urls.py
from django.urls import path
from .views import lowestParent, lowestParent_post
app_name = "parent"

urlpatterns = [
    path('', lowestParent, name='lowest-parent'),
    path('get', lowestParent_post, name='lowest-parent-post')
]

lowestParent/models.py
from django.db import models

# Create your models here.

lowestParent/views.py
from django.shortcuts import render
from homepage.models import TaxonomicUnits, Hierarchy, TaxonUnitTypes
from django.http import JsonResponse, HttpResponseBadRequest
from django.views.decorators.http import require_GET, require_POST
from django.core import serializers


def lowestParent(request):
    return render(request, 'lowestParent/lowestParent.html')


@require_POST
def lowestParent_post(request):
    animal1_string = request.POST.get('animal1')
    animal2_string = request.POST.get('animal2')
    try:
        animal1 = TaxonomicUnits.objects.filter(complete_name__iexact=animal1_string)[0]
        animal2 = TaxonomicUnits.objects.filter(complete_name__iexact=animal2_string)[0]
        if (animal1.rank_id.rank_name.strip() != "Species" or animal1.parent_tsn.rank_id == 0) or (animal2.rank_id.rank_name.strip() != "Species" or animal2.parent_tsn.rank_id == 0):
            raise Exception
    except Exception:
        return HttpResponseBadRequest()
    hierarchy1 = animal1.hierarchy.hierarchy_string.strip().split("-")
    hierarchy2 = animal2.hierarchy.hierarchy_string.strip().split("-")
    hierarchy1.reverse()
    hierarchy2.reverse()
    res1 = None
    res2 = None
    pointer1 = 0
    pointer2 = 0
    while hierarchy1[pointer1] != hierarchy2[pointer2]:
        rank1 = TaxonomicUnits.objects.get(tsn=hierarchy1[pointer1]).rank_id.rank_id
        rank2 = TaxonomicUnits.objects.get(tsn=hierarchy2[pointer2]).rank_id.rank_id

        while rank1 != rank2:
            if rank1 > rank2:
                taxon1 = TaxonomicUnits.objects.get(tsn=hierarchy1[pointer1])
                tmp1 = [{
                    'text': {'name': taxon1.complete_name, 'desc': taxon1.rank_id.rank_name},
                    'HTMLclass': 'the-parent',
                    'children': res1
                }]
                res1 = tmp1

                tmp2 = [{'pseudo': True, 'HTMLclass': 'the-parent', 'children': res2}]
                res2 = tmp2
                pointer1 = pointer1 + 1
            else:
                taxon2 = TaxonomicUnits.objects.get(tsn=hierarchy2[pointer2])
                tmp2 = [{
                    'text': {'name': taxon2.complete_name, 'desc': taxon2.rank_id.rank_name},
                    'HTMLclass': 'the-parent',
                    'children': res2
                }]
                res2 = tmp2

                tmp1 = [{'pseudo': True, 'HTMLclass': 'the-parent', 'children': res1}]
                res1 = tmp1
                pointer2 = pointer2 + 1
            rank1 = TaxonomicUnits.objects.get(tsn=hierarchy1[pointer1]).rank_id.rank_id
            rank2 = TaxonomicUnits.objects.get(tsn=hierarchy2[pointer2]).rank_id.rank_id

        taxon1 = TaxonomicUnits.objects.get(tsn=hierarchy1[pointer1])
        taxon2 = TaxonomicUnits.objects.get(tsn=hierarchy2[pointer2])
        pointer1 = pointer1 + 1
        pointer2 = pointer2 + 1
        tmp1 = [{
            'text': {'name': taxon1.complete_name, 'desc': taxon1.rank_id.rank_name},
            'HTMLclass': 'the-parent',
            'children': res1
        }]
        res1 = tmp1

        tmp2 = [{
            'text': {'name': taxon2.complete_name, 'desc': taxon2.rank_id.rank_name},
            'HTMLclass': 'the-parent',
            'children': res2
        }]
        res2 = tmp2

    child = [res1[0], res2[0]]

    hierarchy = Hierarchy.objects.get(tsn=hierarchy1[pointer1]).hierarchy_string.strip().split("-")
    hierarchy.reverse()
    for i in hierarchy:
        taxon = TaxonomicUnits.objects.get(tsn=i)
        tmp = [{
            'text': {'name': taxon.complete_name, 'desc': taxon.rank_id.rank_name},
            'HTMLclass': 'the-parent',
            'children': child
        }]
        child = tmp

    result = {
        'nodeStructure': child[0]
    }
    return JsonResponse({'result': result})
            

lowestParent/templates/lowestParent/lowestParent.html
{% extends 'base.html' %}
{% load static %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'css/Treant/Treant.css' %}">
    <link rel="stylesheet" href="{% static 'siblings/css/example6.css' %}">
    <link rel="stylesheet" href="{% static 'js/vendor/perfect-scrollbar/perfect-scrollbar.css' %}">
    <link rel="stylesheet" href="{% static 'lowestParent/css/error.css' %}">
{% endblock %}

{% block content %}
    <!-- <div class="gtco-loader"></div> -->
	<div id="page">
	<header id="gtco-header" class="gtco-cover" role="banner" style="background-image: url('{% static 'siblings/images/forest.jpg' %}')">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row">
                    
				<div class="col-md-12 col-md-offset-0 text-center">
                        
					<div class="display-t">
                        <div class="display-tc" data-animate-effect="fadeIn" style="vertical-align: top;">
                            <h1 style="margin-top: 120px">FIND PARENT</h1>
                            <br>
                            <div>
                                <form class="form-inline" id="sibling">
                                    {% csrf_token %}
                                    <input id="animal1" style="color: white; border-color: white; width: 40%" class="form-control bg-info" name="animal1" type="search" placeholder="What is the first animal species?" aria-label="Search" required>
                                    <input id="animal2" style="color: white; border-color: white; width: 40%" class="form-control bg-info" name="animal2" type="search" placeholder="What is the second animal species?" aria-label="Search" required>
                                    <button class="btn btn-outline-success" type="submit" style="font-size: 20px; color: white; background-color: #F75B17" onclick="window.location.href='#OrganiseChart6'">Search</button>
                                  </form>
                            </div>
                            <div>
                                <br>
                                <p style="color: white; font-size: large;">Find Parent feature searches for 
                                    the parent of two different animal 
                                    species. This feature will use forward chaining
                                    and Least Common Subsumer to find the parent 
                                    of the two animal species. Apart from showing 
                                    the parent, it will also show the tree that 
                                    links between the two animal species to the same parent.</p>
                            </div>
                        </div>
                    </div>
                    <div id="error"></div>
				</div>
			</div>
		</div>
    </header>
    <div id="gtco-features">
            <div class="gtco-container">
                    <div class="chart" id="OrganiseChart6"></div>
            </div>
        </div>

    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
    </div>
    </div>
    
{% endblock %}

{% block extrascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.devbridge-autocomplete/1.2.27/jquery.autocomplete.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="{% static 'js/vendor/raphael.js' %}"></script>
    <script src="{% static 'js/treant/Treant.js' %}"></script>
    <script src="{% static 'js/main.js'%}"></script>

    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/vendor/jquery.mousewheel.js' %}"></script>
    <script src="{% static 'js/vendor/perfect-scrollbar/perfect-scrollbar.js' %}"></script>

    <script>
        
    $("form").submit(function() {
        event.preventDefault();
        console.log("SUBMITTED");
        var csrftoken = $("[name=csrfmiddlewaretoken]").val();
        var animal1 = document.getElementById("animal1").value;
        var animal2 = document.getElementById("animal2").value;
        $.ajax({
            headers: { "X-CSRFToken": csrftoken },
            url: "{% url 'parent:lowest-parent-post' %}",
            method: "POST",
            data: {
                animal1: animal1,
                animal2: animal2
            },
            success: function (data) {
                var tree_structure = {
                    chart: {
                        container: "#OrganiseChart6",
                        levelSeparation:    70,
                        siblingSeparation:  35,
                        subTeeSeparation:   70,
                        nodeAlign: "BOTTOM",
                        scrollbar: "fancy",
                        padding: 35,
                        node: { HTMLclass: "evolution-tree" },
                        connectors: {
                            type: "curve",
                            style: {
                                "stroke-width": 2,
                                "stroke-linecap": "round",
                                "stroke": "#ccc"
                            }
                        }
                    }, nodeStructure: data.result.nodeStructure};
                console.log(tree_structure);
                    new Treant(tree_structure);
            },
            error: function () {
                $("#error").append("Please check your input!, input must be species or your species name " +
                    "is still invalid :((")
            }
            })});
    
    </script>
{% endblock %}